//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPENgovSPORTELLO.srVerificaStato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", ConfigurationName="srVerificaStato.VerificaStatoPagamentoBinding")]
    public interface VerificaStatoPagamentoBinding {
        
        // CODEGEN: Generazione di un contratto di messaggio perché l'operazione IdpVerificaStatoPagamenti non è RPC né incapsulata da documenti.
        [System.ServiceModel.OperationContractAttribute(Action="IdpVerificaStatoPagamenti", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IdpVerificaStatoPagamentiResponse IdpVerificaStatoPagamenti(IdpVerificaStatoPagamentiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IdpVerificaStatoPagamenti", ReplyAction="*")]
        System.Threading.Tasks.Task<IdpVerificaStatoPagamentiResponse> IdpVerificaStatoPagamentiAsync(IdpVerificaStatoPagamentiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")]
    public partial class IdpVerificaStatoPagamenti : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdpVerificaStatoPagamento idpVerificaStatoPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="IdpInformativaPagamento", Order=0)]
        public IdpVerificaStatoPagamento IdpVerificaStatoPagamento {
            get {
                return this.idpVerificaStatoPagamentoField;
            }
            set {
                this.idpVerificaStatoPagamentoField = value;
                this.RaisePropertyChanged("IdpVerificaStatoPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdpInformativaPagamento")]
    public partial class IdpVerificaStatoPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdpHeader idpHeaderField;
        
        private IdpVerificaStatoPagamentoIdpBody idpBodyField;
        
        private Versione versioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="IdpHeader", Order=0)]
        public IdpHeader IdpHeader {
            get {
                return this.idpHeaderField;
            }
            set {
                this.idpHeaderField = value;
                this.RaisePropertyChanged("IdpHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdpVerificaStatoPagamentoIdpBody IdpBody {
            get {
                return this.idpBodyField;
            }
            set {
                this.idpBodyField = value;
                this.RaisePropertyChanged("IdpBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Versione Versione {
            get {
                return this.versioneField;
            }
            set {
                this.versioneField = value;
                this.RaisePropertyChanged("Versione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class IdpHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderTRT tRTField;
        
        private HeaderE2E e2EField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HeaderTRT TRT {
            get {
                return this.tRTField;
            }
            set {
                this.tRTField = value;
                this.RaisePropertyChanged("TRT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public HeaderE2E E2E {
            get {
                return this.e2EField;
            }
            set {
                this.e2EField = value;
                this.RaisePropertyChanged("E2E");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class HeaderTRT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceName serviceNameField;
        
        private string msgIdField;
        
        private System.DateTime xMLCrtDtField;
        
        private TRTSender senderField;
        
        private TRTReceiver receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceName ServiceName {
            get {
                return this.serviceNameField;
            }
            set {
                this.serviceNameField = value;
                this.RaisePropertyChanged("ServiceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MsgId {
            get {
                return this.msgIdField;
            }
            set {
                this.msgIdField = value;
                this.RaisePropertyChanged("MsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime XMLCrtDt {
            get {
                return this.xMLCrtDtField;
            }
            set {
                this.xMLCrtDtField = value;
                this.RaisePropertyChanged("XMLCrtDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TRTSender Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public TRTReceiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public enum ServiceName {
        
        /// <remarks/>
        IdpAllineamentoPendenze,
        
        /// <remarks/>
        IdpInformativaPagamento,
        
        /// <remarks/>
        IdpRendicontazioneEnti,
        
        /// <remarks/>
        IdpConfigurazioneEnte,
        
        /// <remarks/>
        IdpAutorizzazioneDiPagamento,
        
        /// <remarks/>
        IdpEstrattoContoDebitorio,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class TRTSender : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string senderIdField;
        
        private string senderSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SenderId {
            get {
                return this.senderIdField;
            }
            set {
                this.senderIdField = value;
                this.RaisePropertyChanged("SenderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SenderSys {
            get {
                return this.senderSysField;
            }
            set {
                this.senderSysField = value;
                this.RaisePropertyChanged("SenderSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpEsito")]
    public partial class Esito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codiceField;
        
        private string descrizioneField;
        
        private string elementoField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Codice {
            get {
                return this.codiceField;
            }
            set {
                this.codiceField = value;
                this.RaisePropertyChanged("Codice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Elemento {
            get {
                return this.elementoField;
            }
            set {
                this.elementoField = value;
                this.RaisePropertyChanged("Elemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class RiferimentoDebito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pendenzaField;
        
        private string tipoDebitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Pendenza {
            get {
                return this.pendenzaField;
            }
            set {
                this.pendenzaField = value;
                this.RaisePropertyChanged("Pendenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoDebito {
            get {
                return this.tipoDebitoField;
            }
            set {
                this.tipoDebitoField = value;
                this.RaisePropertyChanged("TipoDebito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public partial class Allegato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titoloField;
        
        private MIMETypeCode codificaField;
        
        private byte[] contenutoField;
        
        private string idAntifalsificazioneField;
        
        private ContentType tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Titolo {
            get {
                return this.titoloField;
            }
            set {
                this.titoloField = value;
                this.RaisePropertyChanged("Titolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MIMETypeCode Codifica {
            get {
                return this.codificaField;
            }
            set {
                this.codificaField = value;
                this.RaisePropertyChanged("Codifica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] Contenuto {
            get {
                return this.contenutoField;
            }
            set {
                this.contenutoField = value;
                this.RaisePropertyChanged("Contenuto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdAntifalsificazione {
            get {
                return this.idAntifalsificazioneField;
            }
            set {
                this.idAntifalsificazioneField = value;
                this.RaisePropertyChanged("IdAntifalsificazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ContentType Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public enum MIMETypeCode {
        
        /// <remarks/>
        GIF_,
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        JPEG,
        
        /// <remarks/>
        LNK_,
        
        /// <remarks/>
        MSWD,
        
        /// <remarks/>
        MSEX,
        
        /// <remarks/>
        MSPP,
        
        /// <remarks/>
        PDF_,
        
        /// <remarks/>
        PNG_,
        
        /// <remarks/>
        TEXT,
        
        /// <remarks/>
        XML_,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public enum ContentType {
        
        /// <remarks/>
        Documento,
        
        /// <remarks/>
        Ricevuta,
        
        /// <remarks/>
        Quietanza,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class Voce : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descrizioneField;
        
        private decimal importoField;
        
        private TipoVoce tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Importo {
            get {
                return this.importoField;
            }
            set {
                this.importoField = value;
                this.RaisePropertyChanged("Importo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoVoce Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public enum TipoVoce {
        
        /// <remarks/>
        ImportoTransato,
        
        /// <remarks/>
        ImportoAutorizzato,
        
        /// <remarks/>
        ImportoCommissioni,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public partial class DettaglioCanalePagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string filialeField;
        
        private string sportelloField;
        
        private string idTerminaleField;
        
        private string idOperazioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Filiale {
            get {
                return this.filialeField;
            }
            set {
                this.filialeField = value;
                this.RaisePropertyChanged("Filiale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Sportello {
            get {
                return this.sportelloField;
            }
            set {
                this.sportelloField = value;
                this.RaisePropertyChanged("Sportello");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdTerminale {
            get {
                return this.idTerminaleField;
            }
            set {
                this.idTerminaleField = value;
                this.RaisePropertyChanged("IdTerminale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdOperazione {
            get {
                return this.idOperazioneField;
            }
            set {
                this.idOperazioneField = value;
                this.RaisePropertyChanged("IdOperazione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class MezzoPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descrizioneField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class CanalePagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descrizioneField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class Transazione : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CanalePagamento canalePagamentoField;
        
        private MezzoPagamento mezzoPagamentoField;
        
        private DettaglioCanalePagamento dettaglioCanalePagamentoField;
        
        private string idTransazioneField;
        
        private System.DateTime dataOraTransazioneField;
        
        private string codiceAutorizzazioneField;
        
        private System.DateTime dataOraAutorizzazioneField;
        
        private bool dataOraAutorizzazioneFieldSpecified;
        
        private string tipoSicurezzaField;
        
        private decimal importoTransatoField;
        
        private Voce[] dettaglioImportoTransatoField;
        
        private string descrizioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CanalePagamento CanalePagamento {
            get {
                return this.canalePagamentoField;
            }
            set {
                this.canalePagamentoField = value;
                this.RaisePropertyChanged("CanalePagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MezzoPagamento MezzoPagamento {
            get {
                return this.mezzoPagamentoField;
            }
            set {
                this.mezzoPagamentoField = value;
                this.RaisePropertyChanged("MezzoPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DettaglioCanalePagamento DettaglioCanalePagamento {
            get {
                return this.dettaglioCanalePagamentoField;
            }
            set {
                this.dettaglioCanalePagamentoField = value;
                this.RaisePropertyChanged("DettaglioCanalePagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string IdTransazione {
            get {
                return this.idTransazioneField;
            }
            set {
                this.idTransazioneField = value;
                this.RaisePropertyChanged("IdTransazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DataOraTransazione {
            get {
                return this.dataOraTransazioneField;
            }
            set {
                this.dataOraTransazioneField = value;
                this.RaisePropertyChanged("DataOraTransazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CodiceAutorizzazione {
            get {
                return this.codiceAutorizzazioneField;
            }
            set {
                this.codiceAutorizzazioneField = value;
                this.RaisePropertyChanged("CodiceAutorizzazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime DataOraAutorizzazione {
            get {
                return this.dataOraAutorizzazioneField;
            }
            set {
                this.dataOraAutorizzazioneField = value;
                this.RaisePropertyChanged("DataOraAutorizzazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataOraAutorizzazioneSpecified {
            get {
                return this.dataOraAutorizzazioneFieldSpecified;
            }
            set {
                this.dataOraAutorizzazioneFieldSpecified = value;
                this.RaisePropertyChanged("DataOraAutorizzazioneSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TipoSicurezza {
            get {
                return this.tipoSicurezzaField;
            }
            set {
                this.tipoSicurezzaField = value;
                this.RaisePropertyChanged("TipoSicurezza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal ImportoTransato {
            get {
                return this.importoTransatoField;
            }
            set {
                this.importoTransatoField = value;
                this.RaisePropertyChanged("ImportoTransato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Voce[] DettaglioImportoTransato {
            get {
                return this.dettaglioImportoTransatoField;
            }
            set {
                this.dettaglioImportoTransatoField = value;
                this.RaisePropertyChanged("DettaglioImportoTransato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class Pagante : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPaganteField;
        
        private string descrizioneField;
        
        private string tipoField;
        
        public Pagante() {
            this.tipoField = "CodiceFiscale";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdPagante {
            get {
                return this.idPaganteField;
            }
            set {
                this.idPaganteField = value;
                this.RaisePropertyChanged("IdPagante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Descrizione {
            get {
                return this.descrizioneField;
            }
            set {
                this.descrizioneField = value;
                this.RaisePropertyChanged("Descrizione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("CodiceFiscale")]
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("Tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class RiferimentoPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPagamentoField;
        
        private TipoPagamento tipoPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdPagamento {
            get {
                return this.idPagamentoField;
            }
            set {
                this.idPagamentoField = value;
                this.RaisePropertyChanged("IdPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TipoPagamento TipoPagamento {
            get {
                return this.tipoPagamentoField;
            }
            set {
                this.tipoPagamentoField = value;
                this.RaisePropertyChanged("TipoPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public enum TipoPagamento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pagamento a Rate")]
        PagamentoaRate,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pagamento Unico")]
        PagamentoUnico,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class Pagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RiferimentoPagamento riferimentoPagamentoField;
        
        private System.DateTime dataOraPagamentoField;
        
        private System.DateTime dataScadenzaPagamentoField;
        
        private bool dataScadenzaPagamentoFieldSpecified;
        
        private decimal importoField;
        
        private string riferimentoDebitoreField;
        
        private TipoNotifica esitoField;
        
        private Pagante paganteField;
        
        private Transazione transazioneField;
        
        private bool flagQuietanzaCartaceaField;
        
        private bool flagQuietanzaCartaceaFieldSpecified;
        
        private string noteField;
        
        private Allegato allegatoField;
        
        private RiferimentoDebito riferimentoDebitoField;
        
        private string descrizioneCausaleField;
        
        private string identificativoUnivocoVersamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RiferimentoPagamento RiferimentoPagamento {
            get {
                return this.riferimentoPagamentoField;
            }
            set {
                this.riferimentoPagamentoField = value;
                this.RaisePropertyChanged("RiferimentoPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime DataOraPagamento {
            get {
                return this.dataOraPagamentoField;
            }
            set {
                this.dataOraPagamentoField = value;
                this.RaisePropertyChanged("DataOraPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime DataScadenzaPagamento {
            get {
                return this.dataScadenzaPagamentoField;
            }
            set {
                this.dataScadenzaPagamentoField = value;
                this.RaisePropertyChanged("DataScadenzaPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataScadenzaPagamentoSpecified {
            get {
                return this.dataScadenzaPagamentoFieldSpecified;
            }
            set {
                this.dataScadenzaPagamentoFieldSpecified = value;
                this.RaisePropertyChanged("DataScadenzaPagamentoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Importo {
            get {
                return this.importoField;
            }
            set {
                this.importoField = value;
                this.RaisePropertyChanged("Importo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RiferimentoDebitore {
            get {
                return this.riferimentoDebitoreField;
            }
            set {
                this.riferimentoDebitoreField = value;
                this.RaisePropertyChanged("RiferimentoDebitore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public TipoNotifica Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("Esito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Pagante Pagante {
            get {
                return this.paganteField;
            }
            set {
                this.paganteField = value;
                this.RaisePropertyChanged("Pagante");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Transazione Transazione {
            get {
                return this.transazioneField;
            }
            set {
                this.transazioneField = value;
                this.RaisePropertyChanged("Transazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool FlagQuietanzaCartacea {
            get {
                return this.flagQuietanzaCartaceaField;
            }
            set {
                this.flagQuietanzaCartaceaField = value;
                this.RaisePropertyChanged("FlagQuietanzaCartacea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FlagQuietanzaCartaceaSpecified {
            get {
                return this.flagQuietanzaCartaceaFieldSpecified;
            }
            set {
                this.flagQuietanzaCartaceaFieldSpecified = value;
                this.RaisePropertyChanged("FlagQuietanzaCartaceaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public Allegato Allegato {
            get {
                return this.allegatoField;
            }
            set {
                this.allegatoField = value;
                this.RaisePropertyChanged("Allegato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public RiferimentoDebito RiferimentoDebito {
            get {
                return this.riferimentoDebitoField;
            }
            set {
                this.riferimentoDebitoField = value;
                this.RaisePropertyChanged("RiferimentoDebito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DescrizioneCausale {
            get {
                return this.descrizioneCausaleField;
            }
            set {
                this.descrizioneCausaleField = value;
                this.RaisePropertyChanged("DescrizioneCausale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string IdentificativoUnivocoVersamento {
            get {
                return this.identificativoUnivocoVersamentoField;
            }
            set {
                this.identificativoUnivocoVersamentoField = value;
                this.RaisePropertyChanged("IdentificativoUnivocoVersamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public enum TipoNotifica {
        
        /// <remarks/>
        ESEGUITO,
        
        /// <remarks/>
        REGOLATO,
        
        /// <remarks/>
        INCASSO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpEsito")]
    public partial class InformazioniPagamentoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPagamentoField;
        
        private string tipoPendenzaField;
        
        private VerificaStatoPagamentoDettagliato statoField;
        
        private string descrizioneStatoField;
        
        private Pagamento pagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IdPagamento {
            get {
                return this.idPagamentoField;
            }
            set {
                this.idPagamentoField = value;
                this.RaisePropertyChanged("IdPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TipoPendenza {
            get {
                return this.tipoPendenzaField;
            }
            set {
                this.tipoPendenzaField = value;
                this.RaisePropertyChanged("TipoPendenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public VerificaStatoPagamentoDettagliato Stato {
            get {
                return this.statoField;
            }
            set {
                this.statoField = value;
                this.RaisePropertyChanged("Stato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DescrizioneStato {
            get {
                return this.descrizioneStatoField;
            }
            set {
                this.descrizioneStatoField = value;
                this.RaisePropertyChanged("DescrizioneStato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public Pagamento Pagamento {
            get {
                return this.pagamentoField;
            }
            set {
                this.pagamentoField = value;
                this.RaisePropertyChanged("Pagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpEsito")]
    public enum VerificaStatoPagamentoDettagliato {
        
        /// <remarks/>
        POSIZIONE_NON_PRESENTE,
        
        /// <remarks/>
        POSIZIONE_NON_PAGATA,
        
        /// <remarks/>
        POSIZIONE_NON_PAGABILE,
        
        /// <remarks/>
        POSIZIONE_PAGATA,
        
        /// <remarks/>
        POSIZIONE_PAGATA_SBF,
        
        /// <remarks/>
        POSIZIONE_CON_PAG_IN_CORSO,
        
        /// <remarks/>
        POSIZIONE_CON_DOC_EMESSO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpEsito")]
    public partial class StatoPagamentoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idPagamentoField;
        
        private string tipoPendenzaField;
        
        private VerificaStatoPagamento valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IdPagamento {
            get {
                return this.idPagamentoField;
            }
            set {
                this.idPagamentoField = value;
                this.RaisePropertyChanged("IdPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoPendenza {
            get {
                return this.tipoPendenzaField;
            }
            set {
                this.tipoPendenzaField = value;
                this.RaisePropertyChanged("TipoPendenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public VerificaStatoPagamento Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInclude")]
    public enum VerificaStatoPagamento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Posizione non presente")]
        Posizionenonpresente,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Posizione non pagabile")]
        Posizionenonpagabile,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pagamento non eseguito")]
        Pagamentononeseguito,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Pagamento eseguito")]
        Pagamentoeseguito,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpInformativaPagamento")]
    public partial class idPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoPendenzaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoPendenza {
            get {
                return this.tipoPendenzaField;
            }
            set {
                this.tipoPendenzaField = value;
                this.RaisePropertyChanged("TipoPendenza");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class E2EReceiver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e2ERcvrIdField;
        
        private string e2ERcvrSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string E2ERcvrId {
            get {
                return this.e2ERcvrIdField;
            }
            set {
                this.e2ERcvrIdField = value;
                this.RaisePropertyChanged("E2ERcvrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string E2ERcvrSys {
            get {
                return this.e2ERcvrSysField;
            }
            set {
                this.e2ERcvrSysField = value;
                this.RaisePropertyChanged("E2ERcvrSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class E2ESender : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e2ESndrIdField;
        
        private string e2ESndrSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string E2ESndrId {
            get {
                return this.e2ESndrIdField;
            }
            set {
                this.e2ESndrIdField = value;
                this.RaisePropertyChanged("E2ESndrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string E2ESndrSys {
            get {
                return this.e2ESndrSysField;
            }
            set {
                this.e2ESndrSysField = value;
                this.RaisePropertyChanged("E2ESndrSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class HeaderE2E : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string e2ESrvcNmField;
        
        private string e2EMsgIdField;
        
        private System.DateTime xMLCrtDtField;
        
        private E2ESender senderField;
        
        private E2EReceiver receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string E2ESrvcNm {
            get {
                return this.e2ESrvcNmField;
            }
            set {
                this.e2ESrvcNmField = value;
                this.RaisePropertyChanged("E2ESrvcNm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string E2EMsgId {
            get {
                return this.e2EMsgIdField;
            }
            set {
                this.e2EMsgIdField = value;
                this.RaisePropertyChanged("E2EMsgId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime XMLCrtDt {
            get {
                return this.xMLCrtDtField;
            }
            set {
                this.xMLCrtDtField = value;
                this.RaisePropertyChanged("XMLCrtDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public E2ESender Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public E2EReceiver Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpHeader")]
    public partial class TRTReceiver : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string receiverIdField;
        
        private string receiverSysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReceiverId {
            get {
                return this.receiverIdField;
            }
            set {
                this.receiverIdField = value;
                this.RaisePropertyChanged("ReceiverId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiverSys {
            get {
                return this.receiverSysField;
            }
            set {
                this.receiverSysField = value;
                this.RaisePropertyChanged("ReceiverSys");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdpInformativaPagamento")]
    public partial class IdpVerificaStatoPagamentoIdpBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private idPagamento[] idPagamentoField;
        
        private bool richiestaInformazioniPagamentoField;
        
        private bool richiestaInformazioniPagamentoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IdPagamento", Order=0)]
        public idPagamento[] IdPagamento {
            get {
                return this.idPagamentoField;
            }
            set {
                this.idPagamentoField = value;
                this.RaisePropertyChanged("IdPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool richiestaInformazioniPagamento {
            get {
                return this.richiestaInformazioniPagamentoField;
            }
            set {
                this.richiestaInformazioniPagamentoField = value;
                this.RaisePropertyChanged("richiestaInformazioniPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool richiestaInformazioniPagamentoSpecified {
            get {
                return this.richiestaInformazioniPagamentoFieldSpecified;
            }
            set {
                this.richiestaInformazioniPagamentoFieldSpecified = value;
                this.RaisePropertyChanged("richiestaInformazioniPagamentoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="IdpAllineamentoPendenze")]
    public enum Versione {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-00")]
        Item010300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-01")]
        Item010301,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-02")]
        Item010302,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-03")]
        Item010303,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy")]
    public partial class IdpVerificaStatoPagamentiEsito : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdpEsitoVerifica idpEsitoVerificaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="IdpEsito", Order=0)]
        public IdpEsitoVerifica IdpEsitoVerifica {
            get {
                return this.idpEsitoVerificaField;
            }
            set {
                this.idpEsitoVerificaField = value;
                this.RaisePropertyChanged("IdpEsitoVerifica");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdpEsito")]
    public partial class IdpEsitoVerifica : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdpHeader idpHeaderField;
        
        private IdpEsitoVerificaIdpBody idpBodyField;
        
        private Versione1 versioneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="IdpHeader", Order=0)]
        public IdpHeader IdpHeader {
            get {
                return this.idpHeaderField;
            }
            set {
                this.idpHeaderField = value;
                this.RaisePropertyChanged("IdpHeader");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IdpEsitoVerificaIdpBody IdpBody {
            get {
                return this.idpBodyField;
            }
            set {
                this.idpBodyField = value;
                this.RaisePropertyChanged("IdpBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public Versione1 Versione {
            get {
                return this.versioneField;
            }
            set {
                this.versioneField = value;
                this.RaisePropertyChanged("Versione");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="IdpEsito")]
    public partial class IdpEsitoVerificaIdpBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatoPagamentoType[] statoPagamentoField;
        
        private InformazioniPagamentoType[] informazioniPagamentoField;
        
        private Esito esitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StatoPagamento", Order=0)]
        public StatoPagamentoType[] StatoPagamento {
            get {
                return this.statoPagamentoField;
            }
            set {
                this.statoPagamentoField = value;
                this.RaisePropertyChanged("StatoPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InformazioniPagamento", Order=1)]
        public InformazioniPagamentoType[] InformazioniPagamento {
            get {
                return this.informazioniPagamentoField;
            }
            set {
                this.informazioniPagamentoField = value;
                this.RaisePropertyChanged("InformazioniPagamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Esito Esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("Esito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Versione", Namespace="IdpEsito")]
    public enum Versione1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-00")]
        Item010300,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-01")]
        Item010301,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-02")]
        Item010302,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.03-03")]
        Item010303,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdpVerificaStatoPagamentiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", Order=0)]
        public IdpVerificaStatoPagamenti IdpVerificaStatoPagamenti;
        
        public IdpVerificaStatoPagamentiRequest() {
        }
        
        public IdpVerificaStatoPagamentiRequest(IdpVerificaStatoPagamenti IdpVerificaStatoPagamenti) {
            this.IdpVerificaStatoPagamenti = IdpVerificaStatoPagamenti;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IdpVerificaStatoPagamentiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IdpVerificaStatoPagamenti.Esito", Namespace="http://www.cart.rete.toscana.it/servizi/iris_1_1/proxy", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IdpVerificaStatoPagamenti.Esito")]
        public IdpVerificaStatoPagamentiEsito IdpVerificaStatoPagamentiEsito;
        
        public IdpVerificaStatoPagamentiResponse() {
        }
        
        public IdpVerificaStatoPagamentiResponse(IdpVerificaStatoPagamentiEsito IdpVerificaStatoPagamentiEsito) {
            this.IdpVerificaStatoPagamentiEsito = IdpVerificaStatoPagamentiEsito;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerificaStatoPagamentoBindingChannel : VerificaStatoPagamentoBinding, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificaStatoPagamentoBindingClient : System.ServiceModel.ClientBase<VerificaStatoPagamentoBinding>, VerificaStatoPagamentoBinding {
        
        public VerificaStatoPagamentoBindingClient() {
        }
        
        public VerificaStatoPagamentoBindingClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificaStatoPagamentoBindingClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaStatoPagamentoBindingClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaStatoPagamentoBindingClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdpVerificaStatoPagamentiResponse VerificaStatoPagamentoBinding.IdpVerificaStatoPagamenti(IdpVerificaStatoPagamentiRequest request) {
            return base.Channel.IdpVerificaStatoPagamenti(request);
        }
        
        public IdpVerificaStatoPagamentiEsito IdpVerificaStatoPagamenti(IdpVerificaStatoPagamenti IdpVerificaStatoPagamenti1) {
            IdpVerificaStatoPagamentiRequest inValue = new IdpVerificaStatoPagamentiRequest();
            inValue.IdpVerificaStatoPagamenti = IdpVerificaStatoPagamenti1;
            IdpVerificaStatoPagamentiResponse retVal = ((VerificaStatoPagamentoBinding)(this)).IdpVerificaStatoPagamenti(inValue);
            return retVal.IdpVerificaStatoPagamentiEsito;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdpVerificaStatoPagamentiResponse> VerificaStatoPagamentoBinding.IdpVerificaStatoPagamentiAsync(IdpVerificaStatoPagamentiRequest request) {
            return base.Channel.IdpVerificaStatoPagamentiAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdpVerificaStatoPagamentiResponse> IdpVerificaStatoPagamentiAsync(IdpVerificaStatoPagamenti IdpVerificaStatoPagamenti) {
            IdpVerificaStatoPagamentiRequest inValue = new IdpVerificaStatoPagamentiRequest();
            inValue.IdpVerificaStatoPagamenti = IdpVerificaStatoPagamenti;
            return ((VerificaStatoPagamentoBinding)(this)).IdpVerificaStatoPagamentiAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srVerificaStato.wsVerificaStatoSoap")]
    public interface wsVerificaStatoSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento HelloWorldResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HelloWorldResponse HelloWorld(HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync(HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsVerificaStatoSoapChannel : wsVerificaStatoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsVerificaStatoSoapClient : System.ServiceModel.ClientBase<wsVerificaStatoSoap>, wsVerificaStatoSoap {
        
        public wsVerificaStatoSoapClient() {
        }
        
        public wsVerificaStatoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsVerificaStatoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVerificaStatoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsVerificaStatoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWorldResponse wsVerificaStatoSoap.HelloWorld(HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            HelloWorldResponse retVal = ((wsVerificaStatoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWorldResponse> wsVerificaStatoSoap.HelloWorldAsync(HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWorldResponse> HelloWorldAsync() {
            HelloWorldRequest inValue = new HelloWorldRequest();
            inValue.Body = new HelloWorldRequestBody();
            return ((wsVerificaStatoSoap)(this)).HelloWorldAsync(inValue);
        }
    }
}
